export default {
  secret: process.env.TOKEN_SECRET || 'token_test',
  port: process.env.PORT || 3000,
  db: {
    url: process.env.MONGO_URI || 'mongodb://localhost/challangeapi'
  },
  messages: {
    successSignup: 'Successfully registered user',
    loginFailed:'There is no registered user associate to the username or email provided',
    loginError: 'Email or password are wrong',
    loginSuccess: 'Login success',
    profileInfo: 'Profile info',
    tokenExpired:'The token provided has expired you have to login again',
    provideToken:'The action can not be done without login first',
    requireModeratorRole: 'Require moderator role',
    requireAdminRole: 'Require admin role',
    roleValidationError: 'An error ocurred while user validation',
    sonsList:'List of sons',
    sonFound:'Son found',
    listSonLimit:'List of sons max 10',
    sonCreated:'Son Created and registered as User',
    sonUpdated:'Son Updated',
    sonDeleted:'Son Deleted',
    usersList:'List of users',
    userFound:'User found',
    userCreated:'User Created',
    userUpdated:'User updated',
    userDeleted:'User deleted',
    userNotFound:'User not found',
    permissionDenied:'You are not allow to do this action',
    sonByidNotFound: 'There is no son asociate at that id',
    invalidId:'The id is not in the correct format',
    userExist:'The email or username selected are not avaliables',
    invalidRole:'The role provided  does not exist',
    invalidEmail:'The field email has to be in the correct format',
    invalidDni:'The field dni must be a seven digits number and should not contain special characters',
    invalidUsername:'The username must only contain alphanumeric characters',
    invalidPassword:'The password is not strong enough',
    sonUpdateDenied: 'You are allow to modified only your sons'
  }
}